FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .

# Expose the development server port
EXPOSE 5173
EXPOSE 3000

CMD ["npm", "run", "dev"]